title: Felizia
baseURL: "http://localhost:8085"
languageCode: en-us
# googleAnalytics:
summaryLength: 40
SectionPagesMenu: main
DefaultContentLanguage: en
paginate: 5
theme: "Felizia.Arctic"

params:
  author: Brattli Labs
  description: "F# SAFE Website Application Generator"
  searchURL: https://www.google.com/search
  share: true
  banner: "https://photos.smugmug.com/photos/i-B3grh87/0/5f230dc4/X3/i-B3grh87-X3.jpg"
  brand: "/img/safe_favicon.png"
  literate: true
  keywords:
    - SAFE
    - Fable
    - Feliz
    - SSR
    - SPA
    - "F#"
  social:
    facebook: dbrattli


languages:
  en:
    languageName: English
    weight: 1
    params:
      description: "F# SAFE Website Application Generator"

  nb:
    languageName: Norsk
    weight: 2
    params:
      description: "F# SAFE Webside Applikasjonsgenerator"

  # googleAnalytics:
  #  anonymizeIP: true
  #  respectDoNotTrack: true