// <auto-generated />

/// Theme handling is a bit tricky client side as we cannot use reflection to map a string to a type as we do server
/// side. This file will get theme information added and written as `Theme.fs`. If you know a better way to do this
/// then please open an issue.
module Felizia.Theme

let theme = Felizia.Arctic.Theme.theme ()
