// <auto-generated />

/// Theme handling is a bit tricky client side as we cannot use reflection as we do server side.
module Felizia.Theme

open Felizia
open Felizia.Arctic

let theme = {
    Name = "Felizia.Arctic"
    Index = Partials.Index.index
    Single = Partials.SingleView.singleView
    List = Partials.ListView.listView
}
