namespace Felizia

open System.Collections.Generic

open Feliz.ViewEngine
open Thoth.Json.Net

type View = Model -> Dispatch -> ReactElement
type IRouter = IDictionary<Url, View>

type Theme = {
    Name: string
    Index: View
    Single: View
    List: View
}

[<AutoOpen>]
module Extensions =
    type Model
    with
        /// Serialize model into JSON state. We also remove as much as possible and regenerate the information when we Deserialize.
        member this.Serialize () =
            // Clear the model for information that can be regenerated by the client.
            let model = { this with CurrentSite = Site.Empty; CurrentPage = { this.CurrentPage with Paginator = None } }

            // Note we call json serialization twice here, because Elmish's model can be some complicated type instead of
            // pojo. The first one will seriallize the state to a json string, and the second one will seriallize the json
            // string to a js string, so we can deseriallize it by Thoth auto decoder and get the correct types.
            Encode.Auto.toString(0, (Encode.Auto.toString(0, model)))
